# Generated by Django 2.0.4 on 2018-04-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('link_text', models.TextField()),
                ('description', models.TextField()),
                ('time_published', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
