# Generated by Django 2.0.4 on 2018-04-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-time_published'], 'verbose_name_plural': 'News'},
        ),
    ]
